version: 2.1 

orbs:
  go: circleci/go@1.10.0

jobs: 
  build_and_test:
    executor: 
      name: go/default
      tag: '1.19.2'
    steps: 
      - checkout 
      - go/load-cache 
      - go/mod-download 
      - go/save-cache
      - go/test: 
          covermode: atomic
          failfast: true
          race: true

workflows:
  test_my_app:
    jobs: 
      - build_and_test
      